print("**The Ultimate Recipe Maker**")
print()
food = input("Name a food:")
plant = input("Name a plant type:")
method = input("Name a method of cooking:")
description = input("Whats a word to describe burned food:")
item = input("Name a household item:")
print()
print (" **Cool New Recipe!**")
print()
print(method, food, "with", description, plant, "on a bed of", item)